name: Azure CLI Key Vault Access

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  azure-auth:
    runs-on: ubuntu-latest
    steps:

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: 9de2854e-ce2d-422a-9ebf-514077017382
          tenant-id: 0e7f6f8b-dfc2-4a5d-9c14-6f3eb7a8fe8d
          subscription-id: 570d31df-cdb1-4474-85d1-026976153e7e

      - name: Fetch secrets from Azure Key Vault
        run: |
          SECRET_VALUE=$(az keyvault secret show --name "pilot-test-secret" --vault-name "pilot-kv-main" --query "value" -o tsv)
          echo "Fetched secret successfully."
